version: '3.4'

services:
  enqueuer.queueing.api:
    image: ${DOCKER_REGISTRY-}enqueuerqueueingapi
    build:
      context: .
      dockerfile: src/Enqueuer.Queueing.API/Dockerfile
    environment:
      - ConnectionStrings__EventBus=amqp://guest:guest@eventbus:5672
      - EventsDatabase__ConnectionString=mongodb://user:pass@mongodb
    depends_on:
      - eventbus
      - mongodb

  eventbus:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management interface port

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - type: bind
        source: C:/Users/vkurd/EnqueuerData/Queueing/DB
        target: /data/db

  enqueuer.telegram.notifications:
    image: ${DOCKER_REGISTRY-}enqueuertelegramnotifications
    build:
      context: .
      dockerfile: src/Enqueuer.Telegram.Notifications/Dockerfile
    environment:
      - ConnectionStrings__EventBus=amqp://guest:guest@eventbus:5672
      - ConnectionStrings__NotificationsDB=Data Source=/data/NotificationsDB.db
      - TelegramClient__AccessToken=${ENQUEUER_TELEGRAM_BOT_ACCESS_TOKEN}
    depends_on:
      - enqueuer.queueing.api
      - eventbus
    volumes:
      - C:/Users/vkurd/EnqueuerData/Notifications/DB:/data

  enqueuer.telegram.bff:
    image: ${DOCKER_REGISTRY-}enqueuertelegrambff
    build:
      context: .
      dockerfile: src/Enqueuer.Telegram.BFF/Dockerfile
    environment:
      - ConnectionStrings__QueueingAPI=http://enqueuer.queueing.api:8080
      - TelegramClient__AccessToken=${ENQUEUER_TELEGRAM_BOT_ACCESS_TOKEN}
    depends_on:
      - enqueuer.queueing.api

volumes:
  notificationsdb:
