//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enqueuer.Telegram.BFF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Enqueuer.Telegram.BFF.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateQueue_Error_InvalidQueueName {
            get {
                return ResourceManager.GetString("CreateQueue_Error_InvalidQueueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue name is missing. Please write command this way: &quot;/createqueue [queue name]&quot;..
        /// </summary>
        internal static string CreateQueue_Error_MissingQueueName {
            get {
                return ResourceManager.GetString("CreateQueue_Error_MissingQueueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateQueue_Error_PositionMustBePositive {
            get {
                return ResourceManager.GetString("CreateQueue_Error_PositionMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue with the name &quot;{0}&quot; already exists..
        /// </summary>
        internal static string CreateQueue_Error_QueueAlreadyExists {
            get {
                return ResourceManager.GetString("CreateQueue_Error_QueueAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Dequeue_Error_MissingQueueName {
            get {
                return ResourceManager.GetString("Dequeue_Error_MissingQueueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Dequeue_Error_ParticipantIsNotEnqueued {
            get {
                return ResourceManager.GetString("Dequeue_Error_ParticipantIsNotEnqueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Dequeue_Error_QueueDoesNotExist {
            get {
                return ResourceManager.GetString("Dequeue_Error_QueueDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue name is missing. Please write command this way: &quot;/enqueue [queue name] {position}&quot;..
        /// </summary>
        internal static string Enqueue_Error_MissingQueueName {
            get {
                return ResourceManager.GetString("Enqueue_Error_MissingQueueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Enqueue_Error_PositionIsReserved {
            get {
                return ResourceManager.GetString("Enqueue_Error_PositionIsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue with name &quot;{0}&quot; does not exist in this group..
        /// </summary>
        internal static string Enqueue_Error_QueueDoesNotExist {
            get {
                return ResourceManager.GetString("Enqueue_Error_QueueDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already participate in the queue &quot;{0}&quot;..
        /// </summary>
        internal static string Enqueue_Error_UserAlreadyParticipates {
            get {
                return ResourceManager.GetString("Enqueue_Error_UserAlreadyParticipates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred during your request. Please, try again later or contact support..
        /// </summary>
        internal static string General_Error_Internal {
            get {
                return ResourceManager.GetString("General_Error_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This group doesn&apos;t have any queue. If you want to create one, please use the &quot;/createqueue&quot; command..
        /// </summary>
        internal static string Queue_Message_GroupDoesNotHaveAnyQueue {
            get {
                return ResourceManager.GetString("Queue_Message_GroupDoesNotHaveAnyQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To display information about specific queue and list its participants use the &quot;/queue [queue name]&quot; command..
        /// </summary>
        internal static string Queue_Message_ListGroupQueues_Footer {
            get {
                return ResourceManager.GetString("Queue_Message_ListGroupQueues_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This group has these queues:.
        /// </summary>
        internal static string Queue_Message_ListGroupQueues_Header {
            get {
                return ResourceManager.GetString("Queue_Message_ListGroupQueues_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Queue_Message_ListQueueParticipants_Footer {
            get {
                return ResourceManager.GetString("Queue_Message_ListQueueParticipants_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Queue_Message_ListQueueParticipants_Header {
            get {
                return ResourceManager.GetString("Queue_Message_ListQueueParticipants_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue &quot;{0}&quot; is empty. To enlist, please use the &quot;/enqueue {0}&quot; command..
        /// </summary>
        internal static string Queue_Message_QueueIsEmpty {
            get {
                return ResourceManager.GetString("Queue_Message_QueueIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RemoveQueue_Error_MissingQueueName {
            get {
                return ResourceManager.GetString("RemoveQueue_Error_MissingQueueName", resourceCulture);
            }
        }
    }
}
