//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enqueuer.Telegram.Notifications.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Enqueuer.Telegram.Notifications.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueue me!.
        /// </summary>
        internal static string EnqueueMe_Button {
            get {
                return ResourceManager.GetString("EnqueueMe_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue &quot;{0}&quot; already exists in this chat..
        /// </summary>
        internal static string QueueAlreadyExists_Notification {
            get {
                return ResourceManager.GetString("QueueAlreadyExists_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} created new queue &quot;{1}&quot;!.
        /// </summary>
        internal static string QueueCreated_Notification {
            get {
                return ResourceManager.GetString("QueueCreated_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deleted the &quot;{1}&quot; queue. I shall miss it..
        /// </summary>
        internal static string QueueDeleted_Notification {
            get {
                return ResourceManager.GetString("QueueDeleted_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue &quot;{0}&quot; does not exist in the chat..
        /// </summary>
        internal static string QueueDoesNotExist_Notification {
            get {
                return ResourceManager.GetString("QueueDoesNotExist_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position {0} in queue &quot;{1}&quot; is already reserved. Please select another position..
        /// </summary>
        internal static string RequestedPositionIsAlreadyReserved_Notification {
            get {
                return ResourceManager.GetString("RequestedPositionIsAlreadyReserved_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already participates the queue &quot;{1}&quot;!.
        /// </summary>
        internal static string UserAlreadyParticipatesInQueue_Notification {
            get {
                return ResourceManager.GetString("UserAlreadyParticipatesInQueue_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully removed {0} from the queue &quot;{1}&quot;..
        /// </summary>
        internal static string UserDequeuedFromQueue_Notification {
            get {
                return ResourceManager.GetString("UserDequeuedFromQueue_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added {0} to the queue &quot;{1}&quot; to position &quot;{2}&quot;..
        /// </summary>
        internal static string UserEnqueuedAtPosition_Notification {
            get {
                return ResourceManager.GetString("UserEnqueuedAtPosition_Notification", resourceCulture);
            }
        }
    }
}
