// <auto-generated />
using Enqueuer.Telegram.Notifications.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Enqueuer.Telegram.Notifications.Migrations
{
    [DbContext(typeof(NotificationsContext))]
    partial class NotificationsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Enqueuer.Telegram.Notifications.Persistence.Entities.ChatNotificationsConfiguration", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chat_id");

                    b.Property<string>("NotificationsLanguageCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("notifications_language_code");

                    b.HasKey("ChatId")
                        .HasName("pk_chat_configurations");

                    b.HasIndex("NotificationsLanguageCode")
                        .HasDatabaseName("ix_chat_configurations_notifications_language_code");

                    b.ToTable("chat_configurations", (string)null);
                });

            modelBuilder.Entity("Enqueuer.Telegram.Notifications.Persistence.Entities.Language", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.HasKey("Code")
                        .HasName("pk_languages");

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("Enqueuer.Telegram.Notifications.Persistence.Entities.NotificationMessage", b =>
                {
                    b.Property<string>("LanguageCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("language_code");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("LanguageCode", "Key")
                        .HasName("pk_localized_messages");

                    b.ToTable("localized_messages", (string)null);
                });

            modelBuilder.Entity("Enqueuer.Telegram.Notifications.Persistence.Entities.ChatNotificationsConfiguration", b =>
                {
                    b.HasOne("Enqueuer.Telegram.Notifications.Persistence.Entities.Language", "NotificationsLanguage")
                        .WithMany()
                        .HasForeignKey("NotificationsLanguageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_configurations_available_languages_notifications_language_code");

                    b.Navigation("NotificationsLanguage");
                });

            modelBuilder.Entity("Enqueuer.Telegram.Notifications.Persistence.Entities.NotificationMessage", b =>
                {
                    b.HasOne("Enqueuer.Telegram.Notifications.Persistence.Entities.Language", null)
                        .WithMany("LocalizedMessages")
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_localized_messages_available_languages_language_code");
                });

            modelBuilder.Entity("Enqueuer.Telegram.Notifications.Persistence.Entities.Language", b =>
                {
                    b.Navigation("LocalizedMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
