name: .NET Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout code

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'  # specify your .NET version here

    - name: Restore dependencies
      run: dotnet restore EnqueuerOnContainers.sln

    - name: Build
      run: dotnet build EnqueuerOnContainers.sln --no-restore -c Release

    - name: Test
      run: dotnet test EnqueuerOnContainers.sln --no-build -c Release
